java-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/HumanProfileAdapter.java
Fixed problem when null is always returned from profile.getEmailAddress(). 
Mapping attribute name in HumanProfileAdapter is wrong.
=> profile.getEmailAddress() always returns null

java-sdk-api/pom.xml, java-sdk-impl/pom.xml, java-sdk-spring-boot-auto-config/pom.xml
- Update plugin to [1.4.5](https://search.maven.org/#artifactdetails%7Corg.owasp%7Cdependency-check-maven%7C1.4.5%7Cmaven-plugin).
- Disable the .NET scanner since these modules don't use .NET packages and by default it is enabled. When building on non-windows systems that don't have Mono on the executable path this leads to (harmless) build warning appearing in the build log. E.g.
```
[WARNING] An error occurred with the .NET AssemblyAnalyzer;
this can be ignored unless you are scanning .NET DLLs. Please see the log for more details.
```
This warning was suppressed in [later versions ](https://github.com/jeremylong/DependencyCheck/issues/547) anyway, but best to disable features we don't need.
=> Update plugin & disable the .NET OWASP scanner

README.md, java-sdk-api/pom.xml, java-sdk-dummy/pom.xml, java-sdk-impl/pom.xml, java-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/UrlConnector.java, java-sdk-spring-boot-auto-config/README.md, java-sdk-spring-boot-auto-config/pom.xml, java-sdk-spring-boot-auto-config/src/test/java/com/yoti/api/spring/SpringResourceKeyPairSourceTest.java, java-sdk-springboot-example/pom.xml, pom.xml
Thought we should do some house keeping to stay up to date with newer libs where we can that may contain security/bug fixes.
Some of these are passed on as transitive dependencies to clients that depend on us too (e.g. SLF4J), so our users will be happier if they can use later/latest versions with more confidence too.
* Incremented POM versions for new releases and updated dependencies to later versions (where possible). e.g. 1.1 release ready for maven central if/when this is merged and tested.
* BouncyCastle 1.51 -> 1.57 which include bug & security fixes: https://www.bouncycastle.org/releasenotes.html
* SLF4J 1.7.12 -> 1.7.25
* Mockito 1.10.19 -> 2.8.47
* OWASP Plugin 1.4.5 -> 2.1.0a
* Jackson databinding 2.7.5 -> 2.7.9.1 (there are actually later versions in the 2.8.x and 2.9.x series …
=> Dependency updates & house keeping

yoti-sdk-spring-security/README.md, yoti-sdk-spring-security/pom.xml
I'd like to make this lib V1 GA (no longer snapshot). 
If approved I'd like it to be released to maven central when you have time.
=> Making the yoti-sdk-spring-security version 1.0 (non-snapshot).

yoti-sdk-api/pom.xml, yoti-sdk-impl/pom.xml, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/RemoteProfileService.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/RemoteProfileServiceTest.java
Every time a profile exception is raised because of an http error code, the underlying ResourceException is passed as a cause. Clients can leverage that and use the included status code to show consistent messages to users.
Upgraded protobuf-java to 3.5.0 to overcome CVE-2015-5237.
Protobuf people say the issue is solved in 3.4.0, but the owasp plugin still issues an error.
You'll need to pass -Ddependency-check.skip=true in order to install the artifact.
Set version to 1.4-SNAPSHOT so we can test before synchronising to Central.
=> SDK-199: added resource exception as cause of profile exception

yoti-sdk-dummy/pom.xml, yoti-sdk-spring-boot-auto-config/pom.xml
Even after this change, you still need to run with the -Denforcer.skip=true flag
=> FIX-BUILD Update module versions

yoti-sdk-impl/pom.xml, yoti-sdk-spring-security/pom.xml
so the -Denforcer.skip flag doesn't have to be specified on build
=> [SDK-218]: Fixed inter-project dependencies

README.md, pom.xml, yoti-sdk-spring-boot-auto-config/README.md, yoti-sdk-spring-boot-example/README.md, yoti-sdk-spring-security/README.md, yoti-sdk-spring-security/pom.xml
We have version numbers coming out of our ears.  These should be the last of them.
I suggest we merge these to master.
=> API-264: Update remaining build version numbers to 1.4

yoti-sdk-api/src/main/java/com/yoti/api/client/aml/AmlAddressBuilder.java, yoti-sdk-api/src/main/java/com/yoti/api/client/aml/AmlAddressFactory.java, yoti-sdk-api/src/main/java/com/yoti/api/client/aml/AmlProfileBuilder.java, yoti-sdk-api/src/main/java/com/yoti/api/client/aml/AmlProfileFactory.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/aml/SimpleAmlAddressFactory.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/aml/SimpleAmlProfileFactory.java, yoti-sdk-impl/src/main/resources/META-INF/services/com.yoti.api.client.aml.AmlAddressFactory, yoti-sdk-impl/src/main/resources/META-INF/services/com.yoti.api.client.aml.AmlProfileFactory
This commit changes how AML are created.  Now clients can use builder, and the only have to reference classes from the sdk-api project in their code (though they do have to import the sdk-impl project anyway).
=> API-264: Fix creation of AML beans, to match approach take elsewhere

yoti-sdk-impl/suppressed-cves.xml, yoti-sdk-spring-boot-auto-config/suppressed-cves.xml, yoti-sdk-spring-security/suppressed-cves.xml
We now have an additional CVE for jackson-databind.  It seems to be the same issue we agreed to ignore last week.
https://nvd.nist.gov/vuln/detail/CVE-2018-5968
=> API-360: Additional CVE exclusion for jackson

yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/SecureYotiClient.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/YotiConstants.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/factory/SignedMessageFactory.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/util/CryptoUtil.java
We should always specify "BC" when we want to get a BouncyCastle _provided_ component.
=> API-410: Fix resolution of BouncyCastle provided JCA implementations

yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/HumanProfileAdapter.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/HumanProfileAdapterTest.java
This is the shortest, simplest fix for the isAgeOver property.
I have a test in _connect-api-sandbox-service_ that tests this method with the _age_over:xx_ form of the derived property.  That test now passes.  Sandbox doesn't _yet_ support _age_under:xx_ so that still isn't tested.
Also note there is nothing in the getyoti java docs about _isAgeOver_ or the _age_over:xx_ / _age_under:xx_ attributes.  Same goes for the other language SDKs I looked at (which don't appear to support _age_under:xx_ either).
Once this approved I'll release it as 1.4.2-SNAPSHOT.
There are other SDK methods + properties I would to see tests for - DocumentDetails, Structured Address and any property we expect to support with _getAttribute(name, clazz)_
=> API-413: Fix isAgeVerified property

README.md, yoti-sdk-spring-boot-example/README.md, yoti-sdk-spring-security/README.md
Is this a reasonable update for isAgeVerified()?
I'll bump the version numbers to 1.4.2 when it has been released.
=> API-413: Update README for isAgeVerified() bug

pom.xml, yoti-sdk-api/pom.xml, yoti-sdk-api/src/main/java/com/yoti/api/client/DocumentDetails.java, yoti-sdk-impl/pom.xml, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/DocumentDetailsAttributeValue.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/DocumentDetailsAttributeValueTest.java, yoti-sdk-spring-boot-auto-config/pom.xml, yoti-sdk-spring-boot-example/pom.xml, yoti-sdk-spring-security/pom.xml
There was a problem where DocumentDetails would not be parsed if no optional attributes were provided, now fixed.  It now also supports the new _issuingAuthority_ attribute.
For now, the new document types have been included in the enum because removing the enum would be a breaking change.  There's a more detailed discussion in the ticket.
https://lampkicking.atlassian.net/projects/API/issues/API-407
This doesn't have to go in, in its present form.  If we review the ticket and decide to do something about the questions raised then we'll address them first before merging/releasing this.
=> API-407: Support for extended document_details attribute in Java SDK

yoti-sdk-impl/suppressed-cves.xml, yoti-sdk-spring-boot-auto-config/suppressed-cves.xml, yoti-sdk-spring-security/suppressed-cves.xml
Trying to get ready for a JDK deployment (be it for 1.4.3 or 1.5.0), I find we have more CVE problems.
This appears to be the same as the previous jackson library CVEs - we are stuck while we stick Java 1.6.  So I have added the exclusions, and updated API-360 accordingly.
=> API-360: Add more jackson CVE exclusions

README.md, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/AttributeConverter.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/SecureYotiClient.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/util/AnchorCertificateParser.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/SimpleActivityDetailsTest.java, yoti-sdk-spring-boot-auto-config/README.md, yoti-sdk-spring-boot-auto-config/pom.xml, yoti-sdk-spring-boot-example/README.md, yoti-sdk-spring-security/README.md, yoti-sdk-spring-security/pom.xml
Some changes I chose to make, some were forced upon me....
**CVE**
There were some more CVE errors, this time for Spring.  One is from spring-boot, one is spring-core (security).  Rather than add more CVE exclusions,  I have bumped the versions of both to the lowest possible release needed.
**finbugs**
There were a few:
1. It didn't like handling _Exception_
2. It didn't like deserialisation of an object.  It turns out we don't have to use _InputStream_ after all.  Since we have a String, we can just use its bytes and get the BC _ASN1Primitive_ that way.  The tests pass, so I believe it works.
=> API-476: Final tidy up

yoti-sdk-impl/findbugs-rules.xml, yoti-sdk-impl/pom.xml, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/ActivityDetailsFactory.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/AttributeConverter.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/AttributeListConverter.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/DocumentDetailsAttributeParser.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/HumanProfileAdapter.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/ProfileReader.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/ReceiptFetcher.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/SecureYotiClient.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/SecureYotiClientFactory.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/factory/MessageFactory.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/util/Decryption.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/util/DecryptionHelper.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/ActivityDetailsFactoryTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/AttributeListConverterTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/ProfileReaderTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/ReceiptFetcherTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/SecureYotiClientTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/util/CryptoUtil.java, yoti-sdk-parent/pom.xml
Some big changes, but there should be no change to the API or the behaviour of the SDK to anyone using it.
More detail in the ticket.
=> SDK-389: Break up SecureYotiClient

yoti-sdk-api/src/main/java/com/yoti/api/client/DocumentDetails.java, yoti-sdk-api/src/main/java/com/yoti/api/client/HumanProfile.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/ActivityDetailsFactory.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/AttributeConverter.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/AttributeListConverter.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/DocumentDetailsAttributeParser.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/DocumentDetailsAttributeValue.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/HumanProfileAdapter.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/ProfileReader.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/ReceiptFetcher.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/Receipt.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/factory/MessageFactory.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/util/DecryptionHelper.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/AttributeConverterTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/DocumentDetailsAttributeParserTest.java
I've written quite a bit in the ticket.  In short...
We will not use Enums for attribute values.  If we start to return a new value for a given attribute, say a new _Gender_ type or a new _DocumentType_ then parsing that new value will cause an error.  Users of the SDK will be forced to upgrade in order to access the new value, and that's what we're trying to avoid.
=> SDK-394: Stop using Enums for attribute values

yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/AttributeConverter.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/AttributeListConverter.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/DocumentDetailsAttributeParser.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/aml/RemoteAmlService.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/DocumentDetailsAttributeParserTest.java
DocumentDetailsAttributeParsers shall throw an Exception if it receives a malformed DocumetDetails value that it cannot parse.
That Exception will be logged as a WARN by the AttributeListConverter.  The failed attribute is skipped, the Profile will have _null_ for the missing value.
Discussed further in the ticket.
=> SDK-387: Throw Exception for a malformed DocumentDetails attribute value

yoti-sdk-api/pom.xml, yoti-sdk-impl/pom.xml, yoti-sdk-parent/pom.xml, yoti-sdk-spring-boot-auto-config/pom.xml, yoti-sdk-spring-security/pom.xml
We move the gpg + deploy plugins into the parent pom, to ensure that it gets signed + published to maven in future.
=> SDK-451: Fix build, to sign and publish the parent pom

yoti-sdk-spring-boot-example/src/main/resources/templates/fragments.html
This is an easy fix, but I don't know how this has happened.  The original story was SDK-391, and that even has a screen shot displaying sources + verifiers.
My best guess is this change somehow got lost in a merge/rebase before the old SNAPSHOT branch was merged to master.
=> SDK-460: Fix display of sources and verifiers

yoti-sdk-parent/pom.xml
We shall have 2x profiles
- *nexus* for deploying to our internal nexus (use with -Dgpg.skip=true)
- *sonatype* for deploying signed JARs to public sonatype
=> SDK-422: New profile for deploying to /nxs/repository/maven-snaphosts/

README.md, yoti-sdk-api/src/main/java/com/yoti/api/client/AgeVerification.java, yoti-sdk-api/src/main/java/com/yoti/api/client/Anchor.java, yoti-sdk-api/src/main/java/com/yoti/api/client/ApplicationProfile.java, yoti-sdk-api/src/main/java/com/yoti/api/client/HumanProfile.java, yoti-sdk-api/src/main/java/com/yoti/api/client/Profile.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/ApplicationProfileAdapter.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/HumanProfileAdapter.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/SimpleAgeVerification.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/SimpleProfile.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/util/Validation.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/DocumentDetailsAttributeParserTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/HumanProfileAdapterTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/SimpleAgeVerificationTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/SimpleProfileTest.java, yoti-sdk-sandbox/src/main/java/com/yoti/api/client/sandbox/profile/request/YotiTokenRequest.java, yoti-sdk-sandbox/src/main/java/com/yoti/api/client/sandbox/profile/request/attribute/derivation/SandboxAgeVerification.java, yoti-sdk-sandbox/src/test/java/com.yoti.api.client.sandbox/profile/request/YotiTokenRequestTest.java, yoti-sdk-sandbox/src/test/java/com/yoti/api/client/sandbox/profile/request/attribute/derivation/SandboxAgeVerificationTest.java
What do we think of this approach....?
We've decided we want to add support for multiple age-derived-attributes (age_over + age_under) now.  So we have a new _AgeVerification_ interface, and the _HumanProfile_ will now return a list of those wrapping all the age-derived-attributes that it can find.  There are also two helper methods to sweeten it, _findAgeOverVerification(int age)_ and _findAgeUnderVerification(int age)_.
The real meat of this change can be found in _AgeVerification_, _HumanProfile_ and _HumanProfileAdapter_.
Introducing _AgeVerification_ to the api package prompts us to rename the class we already have in the sandbox: _AgeVerification_ > _SandboxAgeVerification_.  This is not a breaking change, since none of the sandbox code has been released yet.  But it will require a …
=> SDK-573: Introduce List<AgeVerification>

yoti-sdk-api/src/main/java/com/yoti/api/client/AgeVerification.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/SimpleAgeVerification.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/SimpleAgeVerificationTest.java, yoti-sdk-sandbox/src/main/java/com/yoti/api/client/sandbox/profile/request/YotiTokenRequest.java, yoti-sdk-sandbox/src/test/java/com.yoti.api.client.sandbox/profile/request/YotiTokenRequestTest.java
We also need a little change in the SDK sandbox code.
I've explained in the SDK-573 ticket.
=> SDK-573: Fix sandbox code to allow multiple derivations of an attribute

yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/RemoteProfileService.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/YotiConstants.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/aml/RemoteAmlService.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/RemoteProfileServiceTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/aml/RemoteAmlServiceTest.java, yoti-sdk-sandbox/src/main/java/com/yoti/api/client/sandbox/YotiSandboxClient.java, yoti-sdk-sandbox/src/test/java/com.yoti.api.client.sandbox/YotiSandboxClientTest.java
We will start sending an additional header, that allows us to see which _version_ of a given SDK people are using.
I did try to find a way of pulling the .jar version in at runtime, but it doesn't work reliably when the code is not in a jar.  I figured it's not really worth it.
=>  SDK-672: Start sending SDK version in the headers

yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/ProfileReader.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/YotiConstants.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/factory/SignedMessageFactory.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/util/DecryptionHelper.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/util/CryptoUtil.java, yoti-sdk-spring-boot-example/src/main/resources/templates/index.html
The real change is bumping the browser.js version.
I've also sneaked in a change for using BouncyCastle's own definition of its provider (i.e. "BC")
=> SDK-631: Update browser.js to 2.2.0 in example project

yoti-sdk-parent/suppressed-cves.xml
See the ticket for fuller details.
Note that we're already using the latest version of this library.  Nothing much we can do other than add an exclusion.
=> SDK-718: Add CVE exclusion for slf4j

yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/ActivityDetailsFactoryTest.java
@echarrod - are we clear that this is what we expect?
At the moment there is a _notNull_ requirement on the _rememberMeId_.  If we get _null_ back, we will blow up.  If we get an _empty_ value (which is a _byte[]_) then we'll be fine, we just return empty String.
=> SDK-816: Ensure test coverage for RememberMeID not being present

yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/AttributeConverter.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/AttributeConverterTest.java
We just parse the value from _byte[]_ to _String_ to _Integer_.
Note that if we get an _empty_ value (protobuf equivalent to null), this will fail.  That's what I'd expect.  If they mean to give us 0 (zero), they should give us 0.  Giving us _empty_ is no good.
=> SDK-864: Add support for parsing INT attribute values

yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/policy/DynamicPolicyBuilder.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/shareurl/policy/SimpleDynamicPolicyBuilder.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/shareurl/policy/SimpleDynamicPolicyBuilderTest.java
- Update the logic in withSelfieAuthorisation and withPinAuthorisation to allow the user to set to false
- Write unit tests to support chaining these methods gives the desired outcome (as well as checking no exceptions are raised if set to false without first turning it on)
=> SDK-1095: Fix Auth Types

yoti-sdk-parent/pom.xml
- Updated jackson library from 2.9.8 -> 2.9.9.2 due to vulnerabilities raised from OWASP.
=> SDK-1099: Update jackson-databind version number due to vulnerabilities

yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/AttributeConverter.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/AttributeConverterTest.java
- Update AttributeConverter to throw a ParseException if the attribute content type is not a string, and has an empty value field.
- Write tests to support this functionality for each attribute content type
=> SDK-854: Only allow string attributes to have empty value

.travis.yml, yoti-sdk-parent/pom.xml
- Update javadoc plugin version 2.18.3 -> 2.23.4
- Update mockito plugin version 3.0.1 -> 3.1.0
- Tested with JDK 11 as problem was with generation of Javadocs
=> SDK-1103: Support for JDK 11

yoti-sdk-spring-boot-example/README.md
- Example project requires Java 8 due to using the streaming API in the callback URL.
- Updated the README to specify Java 8 as required
=> SDK-1102: Update example project README

.travis.yml, yoti-sdk-parent/pom.xml, yoti-sdk-parent/suppressed-cves.xml
- Vunerability CVE-2018-1258 for spring-security has not been fixed in the latest 5.X release.
- Added a dependency-check suppression until this vulnerability has been fixed.
=> SDK-1101: Add dependency-check suppression for spring-security

yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/Base64.java, yoti-sdk-parent/pom.xml
- Building with Java 11 was failing due to using HTML elements that have been deprecated in the HTML5 spec.
- Change these to use HTML5 spec
- Update source target version to 8 for Javadocs
=> SDK-1107: Update Javadocs to HTML5 spec

yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/policy/DynamicPolicyBuilder.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/shareurl/policy/SimpleDynamicPolicyBuilder.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/shareurl/policy/SimpleDynamicPolicyBuilderTest.java
- To bring the Java SDK inline with others, expose the functionality to add a WantedAttribute by name through the DynamicPolicyBuilder
=> SDK-1109: Add ability to add WantedAttribute by name

yoti-sdk-impl/findbugs-rules.xml, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/HttpMethod.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/JsonResourceFetcher.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/RemoteProfileService.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/SignedRequest.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/SignedRequestBuilder.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/aml/RemoteAmlService.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/factory/HeadersFactory.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/factory/PathFactory.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/factory/UnsignedPathFactory.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/qrcode/DynamicSharingService.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/util/Validation.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/AnchorConverterTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/RemoteProfileServiceTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/SignedRequestBuilderTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/aml/RemoteAmlServiceTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/qrcode/DynamicSharingServiceTest.java
* `SignedRequestBuilder` and `SignedRequest` to assist users with creating and executing a signed request
* `UnsignedPathFactory` for returning internal SDK paths without signature query parameters
* Internal SDK now uses SignedRequestBuilder for making calls to Yoti API's
=> SDK-1162: Signed Request Builder

.travis.yml, yoti-sdk-impl/pom.xml, yoti-sdk-parent/pom.xml
* Coveralls support when using travis (found [here](https://coveralls.io/github/getyoti/yoti-java-sdk))
* Updated travis to use `mvn` rather than `mvnw` (as it wasn't using the built in maven cache)
=> SDK-1244: Coveralls

yoti-sdk-spring-boot-example/src/main/resources/templates/profile.html
* Document images should now be shown in the example project profile page instead of String representation of Attribute object
=> SDK-1257: Change example project to show document images

yoti-sdk-api/src/main/java/com/yoti/api/client/Profile.java, yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/policy/WantedAttribute.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/shareurl/policy/SimpleDynamicPolicyBuilder.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/shareurl/policy/SimpleWantedAttribute.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/shareurl/policy/SimpleWantedAttributeBuilder.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/ApplicationProfileAdapter.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/HumanProfileAdapter.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/SimpleProfile.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/shareurl/policy/SimpleWantedAttributeBuilderTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/SimpleProfileTest.java
* `Profile`
* Added methods for getting an attribute by exact name, as the old `getAttribute` method used the same filtering functionality as `findAttributeByName` which checked if the attribute name started with the name supplied.
* Changed the way Attributes are stored within Profile to use a list rather than a map.  This is to support receiving multiple attributes with the same name (i.e. document_images with different constraints)
* `DynamicPolicyBuilder`
* The key of each wanted attribute is now modified if the attribute has a list of constraints attached to it.  This is to support the requesting of the same attribute multiple times with different constraints in Dynamic Scenarios
* `Profile`
* The old `getAttribute` methods have been deprecated in favour of using `getAttributeByName` …
=> SDK-1148: Multiple of the same attribute with different constraints

README.md, pom.xml, yoti-sdk-api/pom.xml, yoti-sdk-impl/pom.xml, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/RemoteProfileService.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/YotiConstants.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/aml/RemoteAmlService.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/qrcode/DynamicSharingService.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/RemoteProfileServiceTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/aml/RemoteAmlServiceTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/qrcode/DynamicSharingServiceTest.java, yoti-sdk-parent/pom.xml, yoti-sdk-sandbox/pom.xml, yoti-sdk-spring-boot-auto-config/README.md, yoti-sdk-spring-boot-auto-config/pom.xml, yoti-sdk-spring-boot-example/README.md, yoti-sdk-spring-boot-example/pom.xml, yoti-sdk-spring-security/README.md, yoti-sdk-spring-security/pom.xml
* Updated exception handling of the Signed Request builder to make error reporting more concise
=> SDK-1278: Refactor exception handling for more concise error reporting

yoti-sdk-impl/findbugs-rules.xml, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/JpegAttributeValue.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/PngAttributeValue.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/ReceiptFetcher.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/ImageResourceFetcher.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/JsonResourceFetcher.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/RawResourceFetcher.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/SignedRequest.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/SignedRequestBuilder.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/SignedRequestResponse.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/YotiConstants.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/ImageResourceFetcherTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/JsonResourceFetcherTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/RawResourceFetcherTest.java, yoti-sdk-parent/pom.xml
* Support for different Content-Types that are used in the Yoti ecosystem (mainly images and binary data used in Doc Scan)
=> SDK-1274: Update Signed Request & Builder

yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/ActivityDetailsFactory.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/ActivityDetailsFactoryTest.java
* `ActivityDetailsFactory.create(...)` now re-throws `ProfileException` when reading extra data, and failing to decrypt the object.
* Any other exception from reading Extra Data (i.e. invalid data entry) will be wrapped silently.
=> SDK-1307: Extra Data Exception

yoti-sdk-parent/pom.xml
* `Yoti` as a developer in the parent POM (this is required to push to sonatype)
=> Release-2.6.0: Add Yoti as a developer in parent POM

README.md, pom.xml, yoti-sdk-api/pom.xml, yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/extension/ThirdPartyAttributeContent.java, yoti-sdk-impl/pom.xml, yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/YotiConstants.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/shareurl/extension/SimpleThirdPartyAttributeExtensionBuilderTest.java, yoti-sdk-parent/pom.xml, yoti-sdk-sandbox/pom.xml, yoti-sdk-spring-boot-auto-config/README.md, yoti-sdk-spring-boot-auto-config/pom.xml, yoti-sdk-spring-boot-example/README.md, yoti-sdk-spring-boot-example/pom.xml, yoti-sdk-spring-security/README.md, yoti-sdk-spring-security/pom.xml
**This fix does not require any changes from an integrators perspective**
* Fixed a bug in `ThirdPartyAttributeContent` extension, whereby the timezone offset on supplied expiry date was being ignored when being converted into UTC date string.
=> Release 2.7.1

yoti-sdk-api/src/main/java/com/yoti/api/client/docs/session/retrieve/CheckResponse.java, yoti-sdk-api/src/main/java/com/yoti/api/client/docs/session/retrieve/GeneratedCheckResponse.java, yoti-sdk-api/src/main/java/com/yoti/api/client/docs/session/retrieve/LivenessResourceResponse.java, yoti-sdk-api/src/main/java/com/yoti/api/client/docs/session/retrieve/TaskResponse.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/docs/session/retrieve/SimpleCheckResponse.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/docs/session/retrieve/SimpleGeneratedCheckResponse.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/docs/session/retrieve/SimpleLivenessResourceResponse.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/docs/session/retrieve/SimpleTaskResponse.java
* This change stops Jackson from throwing away the type property for various response classes in Doc Scan
=> SDK-1548: Expose type properties on doc scan classes

yoti-sdk-api/src/main/java/com/yoti/api/client/docs/session/retrieve/GetSessionResult.java, yoti-sdk-api/src/main/java/com/yoti/api/client/docs/session/retrieve/IdDocumentResourceResponse.java, yoti-sdk-api/src/main/java/com/yoti/api/client/docs/session/retrieve/ResourceContainer.java, yoti-sdk-api/src/main/java/com/yoti/api/client/docs/session/retrieve/TextExtractionTaskResponse.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/docs/session/retrieve/SimpleGetSessionResult.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/docs/session/retrieve/SimpleIdDocumentResourceResponse.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/docs/session/retrieve/SimpleResourceContainer.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/docs/session/retrieve/SimpleResourceResponse.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/docs/session/retrieve/SimpleTaskResponse.java, yoti-sdk-impl/src/main/java/com/yoti/api/client/docs/session/retrieve/SimpleTextExtractionTaskResponse.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/docs/session/retrieve/SimpleGetSessionResultTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/docs/session/retrieve/SimpleIdDocumentResourceResponseTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/docs/session/retrieve/SimpleResourceContainerTest.java, yoti-sdk-impl/src/test/java/com/yoti/api/client/docs/session/retrieve/SimpleTextExtractionTaskResponseTest.java
* `GetSessionResult`
* `getAuthenticityChecks()`
* `getFaceMatchChecks()`
* `getTextDataChecks()`
* `getLivenessChecks()`
* `IdDocumentResourceResponse`
* `getTextExtractionTasks()`
* `ResourceContainer`
* `getZoomLivenessResources()`
* `TextExtractionTaskResponse`
* `getGeneratedTextDataChecks()`
=> SDK-1464: Doc Scan filtering methods

yoti-sdk-sandbox/src/main/java/com/yoti/api/client/sandbox/docs/request/ResponseConfig.java, yoti-sdk-sandbox/src/test/java/com/yoti/api/client/sandbox/docs/request/ResponseConfigTest.java
- Renamed `withCheckReport` to `withCheckReports`
=> SDK-1539: Rename withCheckReport to withCheckReports

yoti-sdk-api/src/main/java/com/yoti/api/client/DigitalIdentityClient.java, yoti-sdk-api/src/main/java/com/yoti/api/client/identity/ShareSession.java, yoti-sdk-api/src/main/java/com/yoti/api/client/identity/ShareSessionNotification.java, yoti-sdk-api/src/main/java/com/yoti/api/client/identity/ShareSessionRequest.java, yoti-sdk-api/src/main/java/com/yoti/api/client/identity/constraint/Constraint.java, yoti-sdk-api/src/main/java/com/yoti/api/client/identity/constraint/PreferredSources.java, yoti-sdk-api/src/main/java/com/yoti/api/client/identity/constraint/SourceConstraint.java, yoti-sdk-api/src/main/java/com/yoti/api/client/identity/extension/BasicExtensionBuilder.java, yoti-sdk-api/src/main/java/com/yoti/api/client/identity/extension/Extension.java, yoti-sdk-api/src/main/java/com/yoti/api/client/identity/extension/ExtensionBuilder.java, yoti-sdk-api/src/main/java/com/yoti/api/client/identity/extension/ExtensionBuilderFactory.java, yoti-sdk-api/src/main/java/com/yoti/api/client/identity/extension/LocationConstraintContent.java, yoti-sdk-api/src/main/java/com/yoti/api/client/identity/extension/LocationConstraintExtensionBuilder.java, yoti-sdk-api/src/main/java/com/yoti/api/client/identity/extension/ThirdPartyAttributeContent.java, yoti-sdk-api/src/main/java/com/yoti/api/client/identity/extension/ThirdPartyAttributeExtensionBuilder.java, yoti-sdk-api/src/main/java/com/yoti/api/client/identity/extension/TransactionalFlowExtensionBuilder.java, yoti-sdk-api/src/main/java/com/yoti/api/client/identity/policy/Policy.java, yoti-sdk-api/src/main/java/com/yoti/api/client/identity/policy/WantedAnchor.java, yoti-sdk-api/src/main/java/com/yoti/api/client/identity/policy/WantedAttribute.java, yoti-sdk-api/src/main/java/com/yoti/api/client/spi/remote/call/YotiConstants.java, yoti-sdk-api/src/main/java/com/yoti/api/client/spi/remote/call/factory/UnsignedPathFactory.java, yoti-sdk-api/src/main/java/com/yoti/api/client/spi/remote/call/identity/DigitalIdentityService.java, yoti-sdk-api/src/main/java/com/yoti/json/ResourceMapper.java, yoti-sdk-api/src/test/java/com/yoti/api/client/DigitalIdentityClientTest.java, yoti-sdk-api/src/test/java/com/yoti/api/client/spi/remote/call/identity/DigitalIdentityServiceTest.java, yoti-sdk-spring-boot-example/src/main/java/com/yoti/api/examples/springboot/DigitalIdentityController.java, yoti-sdk-spring-boot-example/src/main/resources/templates/digital-identity-share.html
The PR seems big but if excluded the duplicated classes, Extensions, Policy, in common with the Dynamic Scenario the new code isn't that much. I had to duplicate those classes because I cannot move them from their original package and neither I want to use a DynamicPolicy obj in the v2 share. When v1 is going to be deprecated the whole package can be dropped. 
The little example just displays the result session id, status and expiration in page.
Next step Qr code creation and the example will show the resulting session and QR code
=> SDK-2231: Add Identity Session creation service

yoti-sdk-api/src/main/java/com/yoti/api/client/identity/policy/WantedAttribute.java, yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/policy/WantedAttribute.java, yoti-sdk-api/src/test/java/com/yoti/api/client/shareurl/policy/WantedAttributeTest.java
The [epic](https://lampkicking.atlassian.net/browse/SDK-2360) suggests to map both `anchors: []` and `alternative_names: []` but turns out the `Attribute.anchors` has been [deprecated](https://github.com/lampkicking/core-api/blob/7da190ab1e4eb2b8c29fe973e80b91f015e91278/sharepubapi_v1/Policy.proto#L129) for years (see [conversation](https://yoti.slack.com/archives/C3B8FSJMV/p1710427120485889) for details)
=> SDK-2364: Map attribute alternative names
