getyoti/yoti-java-sdk

README.md
java-sdk-api/pom.xml
java-sdk-dummy/pom.xml
java-sdk-impl/pom.xml
java-sdk-spring-boot-auto-config/.gitignore
java-sdk-spring-boot-auto-config/README.md
java-sdk-spring-boot-auto-config/pom.xml
java-sdk-spring-boot-auto-config/src/main/java/com/yoti/api/spring/SpringResourceKeyPairSource.java
java-sdk-spring-boot-auto-config/src/main/java/com/yoti/api/spring/YotiClientAutoConfiguration.java
java-sdk-spring-boot-auto-config/src/main/java/com/yoti/api/spring/YotiClientProperties.java
java-sdk-spring-boot-auto-config/src/main/resources/META-INF/spring.factories
java-sdk-spring-boot-auto-config/src/test/java/com/yoti/api/spring/SpringResourceKeyPairSourceTest.java
java-sdk-spring-boot-auto-config/src/test/java/com/yoti/api/spring/YotiClientPropertiesTest.java
java-sdk-springboot-example/pom.xml
java-sdk-springboot-example/src/main/java/com/yoti/api/examples/springboot/YotiLoginController.java
java-sdk-springboot-example/src/main/java/com/yoti/api/examples/springboot/YotiSDKSampleApp.java
java-sdk-springboot-example/src/main/resources/application.yml
java-sdk-springboot-example/src/main/resources/application.yml.plain
pom.xml

Added Spring boot auto configuration module to simplify integration of the Java SDK with Spring Boot based applications. 
- Updated the README.
- Updated the spring boot sample application to use the new library.

Added Spring boot auto configuration module

---

yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/DateAttributeValue.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/SecureYotiClient.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/RemoteProfileService.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/proto/ContentTypeProto.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/DateAttributeValueTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/SecureYotiClientTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/SimpleProfileTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/RemoteProfileServiceTest.java

~~This is only the unit test.  I figured it would make your review easier.~~
Now 3x commits - refactor the tests, add support for JSON, refactor the tests for RemoteProfileService
There's a few more commits to come, amounting to a much larger refactor.  Doing it it in stages might be easier.

API-264 First tidy up the unit test

---

yoti-sdk-impl/suppressed-cves.xml
yoti-sdk-spring-boot-auto-config/suppressed-cves.xml
yoti-sdk-spring-security/suppressed-cves.xml

Details are in API-360
https://lampkicking.atlassian.net/browse/API-360

API-360: CVE exclusion for jackson-databind

---

yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/HumanProfileAdapterTest.java

Nothing big here, but I'm refactoring as I go and reviewing this in stages will make your life slightly easier...

API-357: First tidy up HumanProfileAdapterTest

---

yoti-sdk-api/src/main/java/com/yoti/api/client/HumanProfile.java
yoti-sdk-api/src/main/java/com/yoti/api/client/Profile.java
yoti-sdk-impl/pom.xml
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/ApplicationProfileAdapter.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/HumanProfileAdapter.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/SimpleProfile.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/HumanProfileAdapterTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/SimpleProfileTest.java

Here's the change to add isAgeVerified.
I've also taken this opportunity to update bouncy-castle to latest (1.59)

API-357: Add age verification helper method to HumanProfile

---

README.md
pom.xml
yoti-sdk-api/pom.xml
yoti-sdk-api/src/main/java/com/yoti/api/client/HumanProfile.java
yoti-sdk-impl/pom.xml
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/HumanProfileAdapter.java
yoti-sdk-spring-boot-auto-config/README.md
yoti-sdk-spring-boot-auto-config/pom.xml
yoti-sdk-spring-boot-example/README.md
yoti-sdk-spring-boot-example/pom.xml
yoti-sdk-spring-boot-example/src/main/java/com/yoti/api/examples/springboot/YotiLoginController.java
yoti-sdk-spring-security/README.md
yoti-sdk-spring-security/pom.xml

Didn't make any changes to HumanProfileAdapterTests in the end, as there is no logic in HumanProfileAdapter for GetFullName, it simply returns the attribute.

SDK-264: Added getFullName, deprecated getGivenAndLastNames

---

README.md
yoti-sdk-api/pom.xml
yoti-sdk-impl/pom.xml
yoti-sdk-spring-boot-auto-config/README.md
yoti-sdk-spring-boot-auto-config/pom.xml
yoti-sdk-spring-boot-auto-config/src/main/java/com/yoti/api/spring/YotiClientProperties.java
yoti-sdk-spring-boot-auto-config/src/test/java/com/yoti/api/spring/YotiClientPropertiesTest.java
yoti-sdk-spring-boot-example/README.md
yoti-sdk-spring-boot-example/pom.xml
yoti-sdk-spring-boot-example/src/main/java/com/yoti/api/examples/springboot/YotiLoginController.java
yoti-sdk-spring-boot-example/src/main/resources/application.yml
yoti-sdk-spring-boot-example/src/main/resources/templates/index.html
yoti-sdk-spring-boot-example/src/main/resources/templates/profile.html
yoti-sdk-spring-security/pom.xml

- Added login page to Spring Example, which required adding the application Id to the application.yml
- Added full name & isAgeVerified to example project

[SDK-319]: Added login page to Spring example

---

yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/AttributeConverter.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/HumanProfileAdapter.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/SecureYotiClient.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/SimpleActivityDetails.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/SimpleProfile.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/JsonResourceFetcher.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/Receipt.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/RemoteProfileService.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/aml/RemoteAmlService.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/util/AnchorCertificateParser.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/util/QuietCloseable.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/SecureYotiClientTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/JsonResourceFetcherTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/ReceiptTest.java
yoti-sdk-parent/pom.xml
yoti-sdk-parent/suppressed-cves.xml

Did this 2x weeks ago.  Was sure that I'd opened PR already....

 API-550: Drop Java 6 support, target Java 7

---

yoti-sdk-api/src/main/java/com/yoti/api/attributes/AttributeConstants.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/ApplicationProfileAdapter.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/AttributeConverter.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/HumanProfileAdapter.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/YotiConstants.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/AttributeConverterTest.java

Details are in https://lampkicking.atlassian.net/browse/SDK-396

SDK-396: Move attribute names to an AttributeConstants file

---

yoti-sdk-spring-boot-example/pom.xml
yoti-sdk-spring-boot-example/src/main/java/com/yoti/api/examples/springboot/YotiLoginController.java
yoti-sdk-spring-boot-example/src/main/resources/templates/fragments.html
yoti-sdk-spring-boot-example/src/main/resources/templates/profile.html

Details are in the ticket:
https://lampkicking.atlassian.net/projects/SDK/issues/SDK-391?filter=myopenissues&orderby=updated+DESC

SDK-391: Update Spring demo for v2

---

README.md
yoti-sdk-api/src/main/java/com/yoti/api/client/ActivityDetails.java
yoti-sdk-api/src/main/java/com/yoti/api/client/Anchor.java
yoti-sdk-api/src/main/java/com/yoti/api/client/Attribute.java
yoti-sdk-api/src/main/java/com/yoti/api/client/DateTime.java
yoti-sdk-api/src/main/java/com/yoti/api/client/ProfileException.java
yoti-sdk-api/src/main/java/com/yoti/api/client/SignedTimestamp.java
yoti-sdk-api/src/main/java/com/yoti/api/client/Time.java
yoti-sdk-spring-boot-auto-config/README.md
yoti-sdk-spring-boot-example/README.md
yoti-sdk-spring-security/README.md

Mostly focussed on the readme, but did some api javadocs too
https://lampkicking.atlassian.net/browse/SDK-390

SDK-390: Update documentation for v2

---

README.md
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/AttributeConverter.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/AttributeListConverter.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/DocumentDetailsAttributeValue.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/JsonResourceFetcher.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/ProfileResponse.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/Receipt.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/RemoteProfileService.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/aml/SimpleAmlAddress.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/aml/SimpleAmlProfile.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/aml/SimpleAmlResult.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/util/QuietCloseable.java
yoti-sdk-spring-security/src/main/java/com/yoti/api/spring/security/web/YotiAuthenticationFilter.java

Details are in the ticket: https://lampkicking.atlassian.net/browse/SDK-406

SDK-406: Review logging and use of toString()

---

yoti-sdk-spring-boot-example/README.md

- Was going to mention matching the scenarioID in the button with the one in Dashboard, but it's not currently configurable as a setting.

SDK-399: Updated callback URL text

---

pom.xml
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/DateValue.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/DocumentDetailsAttributeParser.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/DocumentDetailsAttributeValue.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/KeyStreamVisitor.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/SecureYotiClient.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/SimpleActivityDetails.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/JsonResourceFetcher.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/ResourceException.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/YotiConstants.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/factory/PathFactory.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/util/Validation.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/DocumentDetailsAttributeValueTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/RemoteProfileServiceTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/aml/RemoteAmlServiceTest.java
yoti-sdk-parent/pom.xml
yoti-sdk-sandbox/pom.xml
yoti-sdk-sandbox/src/main/java/com/yoti/api/client/sandbox/SandboxException.java
yoti-sdk-sandbox/src/main/java/com/yoti/api/client/sandbox/SandboxPathFactory.java
yoti-sdk-sandbox/src/main/java/com/yoti/api/client/sandbox/YotiSandboxClient.java
yoti-sdk-sandbox/src/main/java/com/yoti/api/client/sandbox/profile/request/YotiTokenRequest.java
yoti-sdk-sandbox/src/main/java/com/yoti/api/client/sandbox/profile/request/attribute/SandboxAttribute.java
yoti-sdk-sandbox/src/main/java/com/yoti/api/client/sandbox/profile/request/attribute/derivation/AgeVerification.java
yoti-sdk-sandbox/src/main/java/com/yoti/api/client/sandbox/profile/response/YotiTokenResponse.java
yoti-sdk-sandbox/src/test/java/com.yoti.api.client.sandbox/YotiSandboxClientTest.java
yoti-sdk-sandbox/src/test/java/com.yoti.api.client.sandbox/profile/request/YotiTokenRequestTest.java
yoti-sdk-sandbox/src/test/java/com/yoti/api/client/sandbox/profile/request/attribute/SandboxAttributeTest.java
yoti-sdk-sandbox/src/test/java/com/yoti/api/client/sandbox/profile/request/attribute/derivation/AgeVerificationTest.java

Described in the ticket: https://lampkicking.atlassian.net/browse/SDK-408

SDK-408: Support the creation of a sandbox token (API-346)

---

README.md
yoti-sdk-api/src/main/java/com/yoti/api/client/ActivityDetails.java
yoti-sdk-api/src/main/java/com/yoti/api/client/Image.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/ImageAttributeValue.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/JpegAttributeValue.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/PngAttributeValue.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/SimpleActivityDetails.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/JpegAttributeValueTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/PngAttributeValueTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/SimpleActivityDetailsTest.java
yoti-sdk-spring-boot-example/src/main/java/com/yoti/api/examples/springboot/YotiLoginController.java

https://lampkicking.atlassian.net/browse/SDK-584 - details
https://lampkicking.atlassian.net/browse/SDK-590 - Java

SDK-590: Standardise Image functionality

---

README.md

When releasing Java SDK 2.1, which included changes to the Image object, the README was updated to show the new approach to AgeVerfications.  The change for AgeVerifications has not been released in Java yet.
For now let's update the README.  The whole set of Java SDK changes can go out as soon as the new sandbox is live.

SS-2: Fix README - multiple AgeVerifications are not released yet

---

yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/proto/AttrProto.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/proto/AttributeListProto.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/proto/EncryptedDataProto.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/proto/SignedTimestampProto.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/proto/SigningProto.java

These are the Java protobuf files, generated from those in the sdk-protobuf repo using the Docker Image

SDK-516: Update to latest protobuf files

---

yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/policy/DynamicPolicyBuilder.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/shareurl/policy/SimpleDynamicPolicyBuilder.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/shareurl/policy/SimpleDynamicPolicyBuilderTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/ActivityDetailsFactoryTest.java

Details are in the Jira ticket.

SDK-832: Minor improvements to DynamicPolicyBuilder

---

yoti-sdk-api/src/main/java/com/yoti/api/client/HumanProfile.java

SDK-989: Add TRANSGENDER to list of possible gender types

---

README.md

- API coverage to README inline with other SDKs - [view here](https://github.com/getyoti/yoti-java-sdk/blob/SDK-1053-documentation/README.md)

SDK-1053: Add API coverage to README

---

yoti-sdk-spring-boot-auto-config/src/main/java/com/yoti/api/spring/YotiClientProperties.java
yoti-sdk-spring-boot-auto-config/src/test/java/com/yoti/api/spring/YotiClientPropertiesTest.java
yoti-sdk-spring-boot-example/src/main/java/com/yoti/api/examples/springboot/YotiLoginController.java
yoti-sdk-spring-boot-example/src/main/resources/application.yml
yoti-sdk-spring-boot-example/src/main/resources/templates/index.html

- Update spring boot example project to use the new QR modal
- Update the LoginController within the example project to pass scenarioId and clientSdkId instead of applicationId
- Update YotiClientProperties class to remove all references of applicationId, and add in scenarioId
- Update tests for YotiClientProperties
- Update default configuration file of spring boot example.

SDK-1042: Update QR Modal

---

README.md

- Update links in project to point to new URL for developer documents

SDK-1081: Update dev docs

---

yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/AnchorConverterTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/TestAnchors.java

- Added a test to ensure the SDK correctly handles unknown anchors as per the example from the Ruby SDK.

SDK-1034: Add unknown anchor test

---

.travis.yml
README.md
yoti-sdk-parent/pom.xml

- Added .travis.yml file to run build verification within travis-ci.com
- Updated README to include build status badge (for master branch)

SDK-882: Add travis file for build verification

---

yoti-sdk-spring-boot-example/src/main/java/com/yoti/api/examples/springboot/YotiLoginController.java
yoti-sdk-spring-boot-example/src/main/resources/static/index.css
yoti-sdk-spring-boot-example/src/main/resources/static/profile.css
yoti-sdk-spring-boot-example/src/main/resources/templates/profile.html

- Updated the example Spring Boot project to include the structured postal address as an attribute
- Updated the static files to be in-line with other SDK's

SDK-1063: Update example project with structured postal address

---

yoti-sdk-api/src/main/java/com/yoti/api/client/Anchor.java

- Updated comments to include possible values for SOURCES and VERIFIERS

SDK-997: Update attribute text

---

.travis.yml
yoti-sdk-spring-boot-example/src/main/java/com/yoti/api/examples/springboot/YotiLoginController.java
yoti-sdk-spring-boot-example/src/main/resources/templates/dynamic-share.html

SDK-747: Add dynamic share example

---

README.md
pom.xml
yoti-sdk-api/pom.xml
yoti-sdk-impl/findbugs-rules.xml
yoti-sdk-impl/pom.xml
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/HttpMethod.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/JsonResourceFetcher.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/RemoteProfileService.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/SignedRequest.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/SignedRequestBuilder.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/YotiConstants.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/aml/RemoteAmlService.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/factory/HeadersFactory.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/factory/PathFactory.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/factory/UnsignedPathFactory.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/qrcode/DynamicSharingService.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/util/Validation.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/AnchorConverterTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/RemoteProfileServiceTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/SignedRequestBuilderTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/aml/RemoteAmlServiceTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/qrcode/DynamicSharingServiceTest.java
yoti-sdk-parent/pom.xml
yoti-sdk-sandbox/pom.xml
yoti-sdk-spring-boot-auto-config/README.md
yoti-sdk-spring-boot-auto-config/pom.xml
yoti-sdk-spring-boot-example/README.md
yoti-sdk-spring-boot-example/pom.xml
yoti-sdk-spring-security/README.md
yoti-sdk-spring-security/pom.xml

* Signed Request with accompanying builder used for creating signed HTTP requests to Yoti services.

Release v2.5.0

---

README.md
pom.xml
yoti-sdk-api/pom.xml
yoti-sdk-impl/pom.xml
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/YotiConstants.java
yoti-sdk-parent/pom.xml
yoti-sdk-sandbox/pom.xml
yoti-sdk-spring-boot-auto-config/README.md
yoti-sdk-spring-boot-auto-config/pom.xml
yoti-sdk-spring-boot-example/README.md
yoti-sdk-spring-boot-example/pom.xml
yoti-sdk-spring-security/README.md
yoti-sdk-spring-security/pom.xml

Bump version number 2.5.0-SNAPSHOT → 2.6.0-SNAPSHOT

Bump version number 2.5.0-SNAPSHOT -> 2.6.0-SNAPSHOT

---

yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/aml/SimpleAmlTest.java

* Added tests for SimpleAml classes

SDK-1248: Add tests for SimpleAml classes

---

yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/constraint/Constraint.java
yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/constraint/ConstraintBuilder.java
yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/constraint/ConstraintBuilderFactory.java
yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/constraint/ConstraintConstants.java
yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/constraint/PreferredSources.java
yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/constraint/SourceConstraint.java
yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/constraint/SourceConstraintBuilder.java
yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/policy/DynamicPolicyBuilder.java
yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/policy/WantedAnchor.java
yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/policy/WantedAnchorBuilder.java
yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/policy/WantedAttribute.java
yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/policy/WantedAttributeBuilder.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/shareurl/constraint/SimpleConstraintBuilderFactory.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/shareurl/constraint/SimpleSourceConstraint.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/shareurl/constraint/SimpleSourceConstraintBuilder.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/shareurl/policy/SimpleDynamicPolicyBuilder.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/shareurl/policy/SimpleWantedAnchor.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/shareurl/policy/SimpleWantedAnchorBuilder.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/shareurl/policy/SimpleWantedAttribute.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/shareurl/policy/SimpleWantedAttributeBuilder.java
yoti-sdk-impl/src/main/resources/META-INF/services/com.yoti.api.client.shareurl.constraint.ConstraintBuilderFactory
yoti-sdk-impl/src/main/resources/META-INF/services/com.yoti.api.client.shareurl.policy.WantedAnchorBuilder
yoti-sdk-impl/src/test/java/com/yoti/api/client/shareurl/constraint/SimpleSourceConstraintBuilderTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/shareurl/policy/SimpleWantedAnchorBuilderTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/shareurl/policy/SimpleWantedAttributeBuilderTest.java

* Support for source constraints for `WantedAttribute` when using Dynamic Scenarios

SDK-1127: Source constraints

---

.pre-commit-config.yaml

* Pre-commit hook to run unit tests and findbugs on commit

SDK-1142: Pre-commit Hook

---

CONTIBUTING.md

* Added contributing file with information for users who wish to contribute to the project

SDK-326: Add contributing file

---

yoti-sdk-impl/src/main/java/com/yoti/api/client/shareurl/policy/SimpleWantedAttribute.java

* Updated `SimpleWantedAttribute` and `SimpleWantedAttributeBuilder` to send minimal JSON payloads to standardise with other SDK's

SDK-1284: Dynamic Scenario JSON Payload

---

yoti-sdk-api/findbugs-rules.xml
yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/extension/ExtensionBuilderFactory.java
yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/extension/ExtensionConstants.java
yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/extension/ThirdPartyAttributeContent.java
yoti-sdk-api/src/main/java/com/yoti/api/client/shareurl/extension/ThirdPartyAttributeExtensionBuilder.java
yoti-sdk-impl/findbugs-rules.xml
yoti-sdk-impl/src/main/java/com/yoti/api/client/shareurl/extension/SimpleExtensionBuilderFactory.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/shareurl/extension/SimpleThirdPartyAttributeExtensionBuilder.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/ActivityDetailsFactory.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/EncryptedDataReader.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/ExtraDataReader.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/IssuingAttribute.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/ProfileReader.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/SimpleAttributeDefinition.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/ThirdPartyAttributeConverter.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/share/ThirdPartyAttributeIssuingRequest.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/share/ThirdPartyAttributeIssuingRequestBuilder.java
yoti-sdk-impl/src/main/resources/META-INF/services/com.yoti.api.client.AttributeDefinition
yoti-sdk-impl/src/test/java/com/yoti/api/client/shareurl/extension/SimpleThirdPartyAttributeExtensionBuilderTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/ActivityDetailsFactoryTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/EncryptedDataReaderTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/ProfileReaderTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/ThirdPartyAttributeConverterTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/call/share/ThirdPartyAttributeIssuingRequestTest.java

SDK-1264: Third Party Attribute Extension

---

.travis.yml
pom.xml
sonar-project.properties
yoti-sdk-sandbox/pom.xml

* Sonarcloud static code analysis

SDK-1394: Add sonarcloud analysis

---

README.md
pom.xml
yoti-sdk-api/pom.xml
yoti-sdk-impl/pom.xml
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/DocumentDetailsAttributeParser.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/YotiConstants.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/DocumentDetailsAttributeParserConsecutiveSpacesTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/DocumentDetailsAttributeParserSpecialCharactersTest.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/spi/remote/DocumentDetailsAttributeParserTest.java
yoti-sdk-parent/pom.xml
yoti-sdk-sandbox/pom.xml
yoti-sdk-spring-boot-auto-config/README.md
yoti-sdk-spring-boot-auto-config/pom.xml
yoti-sdk-spring-boot-example/README.md
yoti-sdk-spring-boot-example/pom.xml
yoti-sdk-spring-security/README.md
yoti-sdk-spring-security/pom.xml

* Updated document details parsing, to allow for other document numbers such as redacted Aadhar

Hotfix-2.6.1

---

yoti-sdk-impl/src/main/java/com/yoti/api/client/docs/DocScanService.java

- Text update after noticing in the other SDK

Update DocScanService JavaDocs

---

yoti-sdk-sandbox/src/main/java/com/yoti/api/client/sandbox/profile/request/attribute/SandboxAttribute.java

* Removed `withOptional` method from `SandboxAttributeBuilder`

SDK-1521: Remove withOptional from sandbox

---

README.md
examples/doc-scan/pom.xml
pom.xml
yoti-sdk-api/pom.xml
yoti-sdk-impl/pom.xml
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/YotiConstants.java
yoti-sdk-parent/pom.xml
yoti-sdk-sandbox/pom.xml
yoti-sdk-spring-boot-auto-config/README.md
yoti-sdk-spring-boot-auto-config/pom.xml
yoti-sdk-spring-boot-example/README.md
yoti-sdk-spring-boot-example/pom.xml
yoti-sdk-spring-security/README.md
yoti-sdk-spring-security/pom.xml

* Merge release branch back into `DEVELOPMENT`

Release → Development

---

yoti-sdk-sandbox/src/main/java/com/yoti/api/client/sandbox/docs/request/SandboxCheckReports.java
yoti-sdk-sandbox/src/main/java/com/yoti/api/client/sandbox/docs/request/check/SandboxDocumentFaceMatchCheck.java
yoti-sdk-sandbox/src/test/java/com/yoti/api/client/sandbox/docs/request/SandboxCheckReportsTest.java
yoti-sdk-sandbox/src/test/java/com/yoti/api/client/sandbox/docs/request/check/SandboxDocumentFaceMatchCheckTest.java

- Renamed `SandboxFaceMatchCheck` to `SandboxDocumentFaceMatchCheck`

SDK-1539: Rename SandboxFaceMatchCheck

---

examples/doc-scan/src/main/resources/templates/index.html

See SDK-1678
Going into master as we want to get this out now, and it doesn't need to be in a release. Will merge into development after.

SDK-1682: Update iframe html to allow full screen

---

examples/doc-scan/README.md
examples/doc-scan/pom.xml
examples/doc-scan/src/main/java/com/yoti/docscan/demo/controller/DocScanController.java
examples/doc-scan/src/main/resources/application.yml.example
examples/doc-scan/src/main/resources/templates/success.html

> Once merged, rebase #215 on `DEVELOPMENT`
- Removed face map download from demo

SDK-1752: Remove face map download from demo

---

examples/doc-scan/src/main/java/com/yoti/docscan/demo/service/DocScanService.java
examples/doc-scan/src/main/resources/templates/success.html

- ID document comparison to demo (for #213)
- Biometric consent timestamp to demo (for #211)

SDK-1721: ID document comparison demo

---

sonar-project.properties
yoti-sdk-impl/src/main/java/com/yoti/api/client/docs/session/create/filters/SimpleRequiredSupplementaryDocumentBuilder.java

- Removed unused import
- Added cpd exclusions

SDK-1712: Address code analysis issues

---

examples/doc-scan/src/main/java/com/yoti/docscan/demo/service/DocScanService.java
examples/doc-scan/src/main/resources/templates/success.html

- Supplementary Documents demo

SDK-1712: Supplementary Documents demo

---

README.md
examples/doc-scan/pom.xml
pom.xml
yoti-sdk-api/pom.xml
yoti-sdk-impl/pom.xml
yoti-sdk-impl/src/main/java/com/yoti/api/client/spi/remote/call/YotiConstants.java
yoti-sdk-parent/pom.xml
yoti-sdk-sandbox/pom.xml
yoti-sdk-spring-boot-auto-config/README.md
yoti-sdk-spring-boot-auto-config/pom.xml
yoti-sdk-spring-boot-example/README.md
yoti-sdk-spring-boot-example/pom.xml
yoti-sdk-spring-security/README.md
yoti-sdk-spring-security/pom.xml

Bump version to `2.12.0-SNAPSHOT`

2.12.0-SNAPSHOT

---

examples/doc-scan/src/main/java/com/yoti/docscan/demo/controller/DocScanController.java
examples/doc-scan/src/main/java/com/yoti/docscan/demo/service/DocScanService.java
examples/doc-scan/src/main/resources/templates/privacy.html
yoti-sdk-api/src/main/java/com/yoti/api/client/docs/session/create/SdkConfig.java
yoti-sdk-api/src/main/java/com/yoti/api/client/docs/session/create/SdkConfigBuilder.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/docs/session/create/SimpleSdkConfig.java
yoti-sdk-impl/src/main/java/com/yoti/api/client/docs/session/create/SimpleSdkConfigBuilder.java
yoti-sdk-impl/src/test/java/com/yoti/api/client/docs/session/create/SimpleSdkConfigBuilderTest.java

- Support for custom privacy policy URL

SDK-1826: Privacy Policy URL

---

yoti-sdk-api/findbugs-rules.xml

NA: Add findbugs exceptions

---

examples/doc-scan/src/main/java/com/yoti/docscan/demo/controller/DocScanErrorController.java
yoti-sdk-spring-boot-example/README.md
yoti-sdk-spring-boot-example/src/main/java/com/yoti/api/examples/springboot/YotiLoginController.java
yoti-sdk-spring-boot-example/src/main/resources/static/profile.css
yoti-sdk-spring-boot-example/src/main/resources/templates/dbs-check.html
yoti-sdk-spring-boot-example/src/main/resources/templates/dynamic-share.html
yoti-sdk-spring-boot-example/src/main/resources/templates/profile.html

Example, available at https://localhost:8443/dbs-check , that builds a standard DBS check via dynamic scenario builder
```
{
"scheme": {
"objective": "STANDARD",
"type": "DBS"
},
"trust_framework": "UK_TFIDA"
}
```

SDK-2135: Add DBS check example page

---

yoti-sdk-api/src/main/java/com/yoti/api/client/spi/remote/ReceiptFetcher.java
yoti-sdk-api/src/main/java/com/yoti/api/client/spi/remote/call/ErrorDetails.java
yoti-sdk-api/src/main/java/com/yoti/api/client/spi/remote/call/ProfileResponse.java
yoti-sdk-api/src/main/java/com/yoti/api/client/spi/remote/call/ProfileService.java
yoti-sdk-api/src/main/java/com/yoti/api/client/spi/remote/call/Receipt.java
yoti-sdk-api/src/test/java/com/yoti/api/client/spi/remote/ReceiptFetcherTest.java
yoti-sdk-api/src/test/java/com/yoti/api/client/spi/remote/call/ErrorDetailsTest.java
yoti-sdk-api/src/test/java/com/yoti/api/client/spi/remote/call/ProfileResponseTest.java
yoti-sdk-api/src/test/java/com/yoti/api/client/spi/remote/call/ProfileServiceTest.java
yoti-sdk-api/src/test/java/com/yoti/api/client/spi/remote/call/ReceiptTest.java

Trying to test a failure receipt. Gonna add more test coverage to make Sonar happy.

SDK-2141: Add error code and description in failure receipt message

---

README.md
examples/doc-scan/pom.xml
pom.xml
yoti-sdk-api/pom.xml
yoti-sdk-api/src/main/java/com/yoti/api/client/spi/remote/call/YotiConstants.java
yoti-sdk-parent/pom.xml
yoti-sdk-sandbox/pom.xml
yoti-sdk-spring-boot-auto-config/README.md
yoti-sdk-spring-boot-auto-config/pom.xml
yoti-sdk-spring-boot-example/README.md
yoti-sdk-spring-boot-example/pom.xml
yoti-sdk-spring-security/README.md
yoti-sdk-spring-security/pom.xml

fix release branch for v3.5.1 is going to be forked from DEVELOPMENT after merging these few libs bumps

Version bumps

---

yoti-sdk-api/src/main/java/com/yoti/api/client/docs/session/create/SessionSpec.java
yoti-sdk-api/src/test/java/com/yoti/api/client/docs/session/create/SessionSpecTest.java

Ticket - https://lampkicking.atlassian.net/browse/SDK-2196

Sdk 2196 - Add support for requesting the profile preview

---

yoti-sdk-api/src/main/java/com/yoti/api/client/docs/DocScanConstants.java
yoti-sdk-api/src/main/java/com/yoti/api/client/docs/session/create/IbvOptions.java
yoti-sdk-api/src/main/java/com/yoti/api/client/docs/session/create/UserPrice.java
yoti-sdk-api/src/test/java/com/yoti/api/client/docs/session/create/IbvOptionsTest.java
yoti-sdk-api/src/test/java/com/yoti/api/client/docs/session/create/UserPriceTest.java

Ticket - https://lampkicking.atlassian.net/browse/SDK-2269

SDK-2269: Add support for providing a user price at session creation

---

examples/doc-scan/src/main/resources/templates/success.html
yoti-sdk-api/src/main/java/com/yoti/api/client/docs/DocScanConstants.java
yoti-sdk-api/src/main/java/com/yoti/api/client/docs/session/retrieve/CheckResponse.java
yoti-sdk-api/src/main/java/com/yoti/api/client/docs/session/retrieve/GetSessionResult.java
yoti-sdk-api/src/main/java/com/yoti/api/client/docs/session/retrieve/SynecticsIdentityFraudCheckResponse.java
yoti-sdk-api/src/test/java/com/yoti/api/client/docs/session/retrieve/GetSessionResultCheckTest.java

Ticket - https://lampkicking.atlassian.net/browse/SDK-2283

SDK-2282: Support Synectics identity Fraud Result

---

yoti-sdk-api/src/main/java/com/yoti/api/client/docs/session/retrieve/configuration/capture/document/SupportedDocumentResponse.java

…guration
Ticket - https://lampkicking.atlassian.net/browse/SDK-2029

Support for non-latin documents when fetching session configuration
